dev:
  password: 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
  theme_id: 128044925170
  store: petri-lindholm-development-store.myshopify.com
  ignore_files:
    - config/settings_data.json

dev-cypress:
  password: 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
  theme_id: 129148911858
  store: petri-lindholm-development-store.myshopify.com
  ignore_files:
    - config/settings_data.json

dev-js:
  password: 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
  theme_id: 130593685746
  store: petri-lindholm-development-store.myshopify.com
  ignore_files:
    - config/settings_data.json

dev-buttons:
  password: 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
  theme_id: 131030843634
  store: petri-lindholm-development-store.myshopify.com
  ignore_files:
    - config/settings_data.json

live:
  password: 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
  theme_id: 120637030642
  store: petri-lindholm-development-store.myshopify.com
  ignore_files:
    - config/settings_data.json

dawn_7:
  password: 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
  theme_id: 136151892210
  store: petri-lindholm-development-store.myshopify.com
  ignore_files:
    - config/settings_data.json

